# Generated from wfloat/assets/registry.json. Do not edit.

REGISTRY_ORIGIN = 'https://registry.wfloat.com'

MODEL_ASSETS = {'HuggingFaceTB/SmolLM2-360M-Instruct': {'family': 'smollm',
                                         'model': {'path': '/models/HuggingFaceTB/SmolLM2-360M-Instruct/model.Q4_K_M.gguf',
                                                   'sha256': '75c4346ef9e855ed630f80078a2430cf63aaca599e340360998a313070fcdc47'}},
 'UsefulSensors/moonshine-tiny': {'cached_decoder': {'path': '/models/UsefulSensors/moonshine-tiny/cached_decoder.int8.onnx',
                                                     'sha256': None},
                                  'encoder': {'path': '/models/UsefulSensors/moonshine-tiny/encoder.int8.onnx',
                                              'sha256': None},
                                  'family': 'moonshine',
                                  'preprocessor': {'path': '/models/UsefulSensors/moonshine-tiny/preprocessor.onnx',
                                                   'sha256': None},
                                  'tokens': {'path': '/models/UsefulSensors/moonshine-tiny/tokens.txt',
                                             'sha256': None},
                                  'uncached_decoder': {'path': '/models/UsefulSensors/moonshine-tiny/uncached_decoder.int8.onnx',
                                                       'sha256': None}},
 'k2-fsa/streaming-zipformer-en': {'decoder': {'path': '/models/k2-fsa/streaming-zipformer-en/decoder.onnx',
                                               'sha256': None},
                                   'encoder': {'path': '/models/k2-fsa/streaming-zipformer-en/encoder.int8.onnx',
                                               'sha256': None},
                                   'family': 'zipformer-transducer',
                                   'joiner': {'path': '/models/k2-fsa/streaming-zipformer-en/joiner.onnx',
                                              'sha256': None},
                                   'tokens': {'path': '/models/k2-fsa/streaming-zipformer-en/tokens.txt',
                                              'sha256': None}},
 'openai/whisper-tiny-en': {'decoder': {'path': '/models/openai/whisper-tiny-en/decoder.int8.onnx',
                                        'sha256': None},
                            'encoder': {'path': '/models/openai/whisper-tiny-en/encoder.int8.onnx',
                                        'sha256': None},
                            'family': 'whisper',
                            'tokens': {'path': '/models/openai/whisper-tiny-en/tokens.txt',
                                       'sha256': None}},
 'snakers4/silero-vad': {'family': 'silero-vad',
                         'model': {'path': '/models/snakers4/silero-vad/model.onnx',
                                   'sha256': None}},
 'wfloat/wfloat-tts': {'model_onnx': {'path': '/models/wfloat/wfloat-tts/model.onnx',
                                      'sha256': 'a7e65773a29499b80a393bbe08af3507e18f6ef95faa0eaf7cb4ba353c8693ae'},
                       'model_tokens': {'path': '/models/wfloat/wfloat-tts/tokens.txt',
                                        'sha256': '96fd291bede0544469d4d8935d462fdd6dc947f22ad47369753e1a82db3d748e'}}}

SHARED_ASSETS = {'espeak_ng_data_aar': {'path': '/assets/espeak-ng-data/espeak-ng-data.aar',
                        'sha256': 'a526b72e81cb1a17e07f55ca0117bba8fbcac7ccd2fa502c61be926eafeaf64e'},
 'espeak_ng_data_zip': {'path': '/assets/espeak-ng-data/espeak-ng-data.zip',
                        'sha256': '56c2879ab1ab44c594c78f34e76c50cf1dd7b8f6ca0ca2634b6766a6edb32add'}}
