import {
  loadLanguageModel,
  loadTextToSpeech,
  loadSpeechToText,
  loadStreamingSpeechToText,
  loadVoiceActivityDetection,
  downloadModel,
  deleteModelAssets,
  defineTool,
  toolResult,
  SPEAKER_IDS,
  VALID_EMOTIONS,
  VALID_SIDS,
  createMicrophoneCapture,
  loadLlmModel,
  loadSttModel,
  loadTtsModel,
  loadVadModel,
} from "@wfloat/wfloat-web";

window.__wfloatSmoke = {
  loadLanguageModel,
  loadTextToSpeech,
  loadSpeechToText,
  loadStreamingSpeechToText,
  loadVoiceActivityDetection,
  downloadModel,
  deleteModelAssets,
  defineTool,
  toolResult,
  createMicrophoneCapture,
  loadLlmModel,
  loadSttModel,
  loadTtsModel,
  loadVadModel,
  speakerCount: Object.keys(SPEAKER_IDS).length,
  emotionCount: VALID_EMOTIONS.length,
  sidCount: VALID_SIDS.length,
};
