// @ts-ignore Generated by scripts/build-worker-inline.mjs.
import workerCode from "./worker-inline.js";

const workerBlob = new Blob([workerCode], { type: "text/javascript" });
const workerUrl = URL.createObjectURL(workerBlob);

export function createWfloatWorker(): Worker {
  return new Worker(workerUrl, { type: "module" });
}
