import type { EmscriptenModule, FS } from "./emscripten.js";
// @ts-ignore Generated by scripts/build-llama-wasm.sh.
import createWfloatLlamaModule from "./wfloat-llama-wasm.js";

export type LlamaModuleConfig = {
  locateFile?: (path: string) => string;
  print?: (text: string) => void;
  printErr?: (text: string) => void;
  onAbort?: (what: unknown) => void;
  [key: string]: unknown;
};

export interface LlamaModule extends EmscriptenModule {
  lengthBytesUTF8(str: string): number;
  stringToUTF8(str: string, outPtr: number, maxBytesToWrite: number): void;
  UTF8ToString(ptr: number): string;
  addFunction(func: Function, sig: string): number;
  removeFunction(ptr: number): void;
  setValue(ptr: number, value: number, type: "i8*" | "i32" | "float"): void;
  getValue(ptr: number, type: "i8*" | "i32" | "float"): number;
  HEAPU32: Uint32Array;
  FS: typeof FS;

  _wfloat_llama_last_error(): number;
  _wfloat_llama_free_string(value: number): void;
  _wfloat_llama_model_create(
    modelPath: number,
    contextSize: number,
    numThreads: number,
    outHandle: number,
  ): number;
  _wfloat_llama_model_destroy(handle: number): void;
  _wfloat_llama_model_format_chat(
    handle: number,
    roles: number,
    contents: number,
    messageCount: number,
    addGenerationPrompt: number,
    chatTemplateFormat: number,
    outUsedFallback: number,
  ): number;
  _wfloat_llama_model_generate_json(
    handle: number,
    prompt: number,
    maxTokens: number,
    temperature: number,
    topP: number,
    topK: number,
    repeatPenalty: number,
    seed: number,
    tokenCallback: number,
    userData: number,
  ): number;
}

export type LlamaGenerationOptions = {
  maxTokens?: number;
  temperature?: number;
  topP?: number;
  topK?: number;
  repeatPenalty?: number;
  seed?: number;
};

export type LlamaGenerationResult = {
  text: string;
  finishReason: string;
  promptTokenCount: number;
  completionTokenCount: number;
  json: string;
};

export type LlamaTokenEvent = {
  text: string;
  tokenIndex: number;
  tokenId: number;
  isDone: boolean;
};

export type LlamaChatMessage = {
  role: string;
  content: string;
};

export type LlamaFormattedChat = {
  prompt: string;
  usedFallback: boolean;
};

export type LlamaChatTemplateFormat = "gguf" | "chatml";

export type LlamaGenerateCallback = (event: LlamaTokenEvent) => boolean | void;

const POINTER_SIZE = 4;

function lastError(module: LlamaModule): string {
  const ptr = module._wfloat_llama_last_error();
  return ptr ? module.UTF8ToString(ptr) : "Unknown llama.cpp error.";
}

function allocUtf8(module: LlamaModule, value: string): number {
  const size = module.lengthBytesUTF8(value) + 1;
  const ptr = module._malloc(size);
  if (!ptr) {
    throw new Error("Out of memory allocating UTF-8 string.");
  }
  module.stringToUTF8(value, ptr, size);
  return ptr;
}

function normalizePositiveInt(value: number | undefined, defaultValue: number): number {
  return typeof value === "number" && Number.isFinite(value) && value > 0
    ? Math.trunc(value)
    : defaultValue;
}

function normalizePositiveNumber(value: number | undefined, defaultValue: number): number {
  return typeof value === "number" && Number.isFinite(value) && value > 0
    ? value
    : defaultValue;
}

function normalizeNonNegativeNumber(value: number | undefined, defaultValue: number): number {
  return typeof value === "number" && Number.isFinite(value) && value >= 0
    ? value
    : defaultValue;
}

function normalizeSeed(value: number | undefined): number {
  return typeof value === "number" && Number.isFinite(value) ? Math.trunc(value) : 0;
}

export async function createLlamaModule(config: LlamaModuleConfig): Promise<LlamaModule> {
  return (await createWfloatLlamaModule(config)) as LlamaModule;
}

export class LlamaWasmModel {
  private constructor(
    private readonly module: LlamaModule,
    private handle: number,
  ) {}

  static create(
    module: LlamaModule,
    modelPath: string,
    contextSize: number,
    numThreads: number,
  ): LlamaWasmModel {
    const modelPathPtr = allocUtf8(module, modelPath);
    const outHandlePtr = module._malloc(POINTER_SIZE);
    if (!outHandlePtr) {
      module._free(modelPathPtr);
      throw new Error("Out of memory allocating llama.cpp handle pointer.");
    }

    try {
      module.setValue(outHandlePtr, 0, "i8*");
      const rc = module._wfloat_llama_model_create(
        modelPathPtr,
        normalizePositiveInt(contextSize, 2048),
        normalizePositiveInt(numThreads, 1),
        outHandlePtr,
      );
      if (rc !== 0) {
        throw new Error(lastError(module));
      }

      const handle = module.getValue(outHandlePtr, "i8*");
      if (!handle) {
        throw new Error("llama.cpp returned an empty model handle.");
      }

      return new LlamaWasmModel(module, handle);
    } finally {
      module._free(modelPathPtr);
      module._free(outHandlePtr);
    }
  }

  free(): void {
    if (!this.handle) {
      return;
    }
    this.module._wfloat_llama_model_destroy(this.handle);
    this.handle = 0;
  }

  formatChat(
    messages: LlamaChatMessage[],
    addGenerationPrompt = true,
    chatTemplateFormat: LlamaChatTemplateFormat = "gguf",
  ): LlamaFormattedChat {
    if (!this.handle) {
      throw new Error("LLM model has been freed.");
    }
    if (messages.length === 0) {
      throw new Error("At least one chat message is required.");
    }

    const rolePtrs: number[] = [];
    const contentPtrs: number[] = [];
    const rolesArrayPtr = this.module._malloc(messages.length * POINTER_SIZE);
    const contentsArrayPtr = this.module._malloc(messages.length * POINTER_SIZE);
    const usedFallbackPtr = this.module._malloc(4);

    if (!rolesArrayPtr || !contentsArrayPtr || !usedFallbackPtr) {
      if (rolesArrayPtr) this.module._free(rolesArrayPtr);
      if (contentsArrayPtr) this.module._free(contentsArrayPtr);
      if (usedFallbackPtr) this.module._free(usedFallbackPtr);
      throw new Error("Out of memory allocating chat formatting buffers.");
    }

    try {
      this.module.setValue(usedFallbackPtr, 0, "i32");
      for (let index = 0; index < messages.length; index += 1) {
        const rolePtr = allocUtf8(this.module, messages[index].role);
        const contentPtr = allocUtf8(this.module, messages[index].content);
        rolePtrs.push(rolePtr);
        contentPtrs.push(contentPtr);
        this.module.setValue(rolesArrayPtr + index * POINTER_SIZE, rolePtr, "i8*");
        this.module.setValue(contentsArrayPtr + index * POINTER_SIZE, contentPtr, "i8*");
      }

      const resultPtr = this.module._wfloat_llama_model_format_chat(
        this.handle,
        rolesArrayPtr,
        contentsArrayPtr,
        messages.length,
        addGenerationPrompt ? 1 : 0,
        chatTemplateFormat === "chatml" ? 1 : 0,
        usedFallbackPtr,
      );
      if (!resultPtr) {
        throw new Error(lastError(this.module));
      }

      try {
        return {
          prompt: this.module.UTF8ToString(resultPtr),
          usedFallback: this.module.getValue(usedFallbackPtr, "i32") !== 0,
        };
      } finally {
        this.module._wfloat_llama_free_string(resultPtr);
      }
    } finally {
      for (const ptr of rolePtrs) this.module._free(ptr);
      for (const ptr of contentPtrs) this.module._free(ptr);
      this.module._free(rolesArrayPtr);
      this.module._free(contentsArrayPtr);
      this.module._free(usedFallbackPtr);
    }
  }

  generate(
    prompt: string,
    options: LlamaGenerationOptions = {},
    onToken?: LlamaGenerateCallback,
  ): LlamaGenerationResult {
    if (!this.handle) {
      throw new Error("LLM model has been freed.");
    }

    const promptPtr = allocUtf8(this.module, prompt);
    let callbackPtr = 0;
    let callbackError: unknown = null;
    try {
      if (onToken) {
        callbackPtr = this.module.addFunction(
          (textPtr: number, tokenIndex: number, tokenId: number) => {
            try {
              const shouldContinue = onToken({
                text: textPtr ? this.module.UTF8ToString(textPtr) : "",
                tokenIndex,
                tokenId,
                isDone: tokenId < 0,
              });
              return shouldContinue === false ? 0 : 1;
            } catch (error) {
              callbackError = error;
              return 0;
            }
          },
          "iiiii",
        );
      }

      const resultPtr = this.module._wfloat_llama_model_generate_json(
        this.handle,
        promptPtr,
        normalizePositiveInt(options.maxTokens, 128),
        normalizeNonNegativeNumber(options.temperature, 0.8),
        normalizePositiveNumber(options.topP, 0.95),
        normalizePositiveInt(options.topK, 40),
        normalizePositiveNumber(options.repeatPenalty, 1.0),
        normalizeSeed(options.seed),
        callbackPtr,
        0,
      );
      if (!resultPtr) {
        throw new Error(lastError(this.module));
      }

      try {
        if (callbackError !== null) {
          throw callbackError;
        }
        const json = this.module.UTF8ToString(resultPtr);
        const parsed = JSON.parse(json) as Omit<LlamaGenerationResult, "json">;
        return {
          text: typeof parsed.text === "string" ? parsed.text : "",
          finishReason:
            typeof parsed.finishReason === "string" ? parsed.finishReason : "unknown",
          promptTokenCount:
            typeof parsed.promptTokenCount === "number" ? parsed.promptTokenCount : 0,
          completionTokenCount:
            typeof parsed.completionTokenCount === "number" ? parsed.completionTokenCount : 0,
          json,
        };
      } finally {
        this.module._wfloat_llama_free_string(resultPtr);
      }
    } finally {
      if (callbackPtr) {
        this.module.removeFunction(callbackPtr);
      }
      this.module._free(promptPtr);
    }
  }
}
